version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - ./backend:/backend
    command: uvicorn app:app --host 0.0.0.0 --port 9000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend/src:/frontend/src

networks:
  app-network:
    driver: bridge
