services:
  - type: web
    name: backend
    runtime: go
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
  - type: web
    name: frontend
    runtime: docker
    rootDir: community/docker
    dockerfilePath: ./Dockerfile
    dockerContext: .